[workspace]
resolver = "2"
members = [ 
    # Applications
    "kaonic-commd",
    "kaonic-commd-cli",
    "kaonic-factory",
    "kaonic-iperf",
    "kaonic-linktest",
    "kaonic-spitest",

    # Integration
    "kaonic-ctrl", 

    # Hardware BSP
    "kaonic-radio",

    # Algorithms
    "kaonic-net",
    "kaonic-frame",
    "kaonic-crc",

    # Drivers
    "radio-rf215",
    "radio-common"
]

# exclude = ["kaonic-gui"]

[profile.release]
opt-level = 3          # max speed (default for release; explicit)
lto = "fat"            # whole-program inlining across crates
codegen-units = 1      # let LTO see everything; better codegen, slower compile
panic = "abort"        # drop unwinding tables/landing pads: smaller + slightly faster
strip = true           # strip symbols from the shipped binary

